{% set version = "2023.2.0" %}


package:
  name: distributed
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/distributed/distributed-{{ version }}.tar.gz
  sha256: 8b3c71273b3b346e6e106762b932c745237390c29d7257479073e95299d07dda

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    # Old style CLI
    - dask-scheduler = distributed.cli.dask_scheduler:main
    - dask-ssh = distributed.cli.dask_ssh:main
    - dask-worker = distributed.cli.dask_worker:main

requirements:
  host:
    - python >=3.8
    - pip
    - dask-core {{ version }}
  run:
    - python >=3.8
    - click >=7.0
    - cloudpickle >=1.5.0
    - cytoolz >=0.10.0
    - {{ pin_compatible('dask-core', max_pin='x.x.x') }}
    - jinja2 >=2.10.3
    - locket >=1.0.0
    - msgpack-python >=1.0.0
    - packaging >=20.0
    - psutil >=5.7.0
    - pyyaml >=5.3.1
    - sortedcontainers >=2.0.5
    - tblib >=1.6.0
    - toolz >=0.10.0
    - tornado >=6.0.3
    - urllib3 >=1.24.3
    - zict >=2.1.0
  run_constrained:
    - openssl !=1.1.1e

test:
  imports:
    - distributed
    - distributed.cli
    - distributed.comm
    - distributed.deploy
    - distributed.diagnostics
    - distributed.protocol
  commands:
    - pip check
    - dask-scheduler --help
    - dask-ssh --help
    - dask-worker --help
    - dask scheduler --help
    - dask ssh --help
    - dask worker --help
    - dask spec --help
  requires:
    - pip

about:
  home: https://distributed.dask.org
  summary: Distributed scheduler for Dask
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  description: |
    Distributed is a lightweight library for distributed computing in Python.
    It extends both the concurrent.futures and dask APIs to moderate sized
    clusters.
  doc_url: https://distributed.dask.org
  doc_source_url: https://github.com/dask/distributed/blob/main/docs/source/index.rst
  dev_url: https://github.com/dask/distributed

extra:
  recipe-maintainers:
    - mrocklin
    - jcrist
    - martindurant
    - jakirkham
    - marcelotrevisani
    - ogrisel
    - tomaugspurger
    - jrbourbeau
    - charlesbluca
