{% set version = "2022.7.1" %}


package:
  name: distributed
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/57/f6/bb2532524de2bad548d5a0d731659389dc9fb3483b18715fa3c359c4111c/distributed-{{ version }}.tar.gz
  sha256: 2c5747a177f228270f00a99e9dff51cc0cf3cfd1e768fe858484fcf65e561bd3

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - dask-scheduler = distributed.cli.dask_scheduler:main
    - dask-ssh = distributed.cli.dask_ssh:main
    - dask-worker = distributed.cli.dask_worker:main

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - click >=6.6
    - cloudpickle >=1.5.0
    - cytoolz >=0.8.2
    - dask-core {{ version }}
    - jinja2
    - locket >=1.0.0
    - msgpack-python >=0.6.0
    - packaging >=20.0
    - psutil >=5.0
    - pyyaml
    - sortedcontainers !=2.0.0,!=2.0.1
    - tblib >=1.6.0
    - toolz >=0.8.2
    - tornado >=6.0.3,<6.2
    - urllib3
    - zict >=0.1.3
  run_constrained:
    - openssl !=1.1.1e

test:
  imports:
    - distributed
    - distributed.cli
    - distributed.comm
    - distributed.deploy
    - distributed.diagnostics
    - distributed.protocol
  commands:
    - pip check
    - dask-scheduler --help
    - dask-ssh --help
    - dask-worker --help
  requires:
    - pip

about:
  home: https://distributed.dask.org
  summary: Distributed scheduler for Dask
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  description: |
    Distributed is a lightweight library for distributed computing in Python.
    It extends both the concurrent.futures and dask APIs to moderate sized
    clusters.
  doc_url: https://distributed.dask.org
  doc_source_url: https://github.com/dask/distributed/blob/main/docs/source/index.rst
  dev_url: https://github.com/dask/distributed

extra:
  recipe-maintainers:
    - mrocklin
    - jcrist
    - martindurant
    - jakirkham
    - marcelotrevisani
    - ogrisel
    - tomaugspurger
    - jrbourbeau
